wandb_version: 1

action_repeat:
  value: 2
agent:
  value: hyper_ddpg_rnd
batch_size:
  value: 256
num_train_frames:
  value: 100010
obs_type:
  value: pixels
seed:
  value: 1
snapshot_ts:
  value: 100000
task:
  value: walker_stand
