wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.15
      5: 0.11.1
      8:
      - 5
action_repeat:
  desc: null
  value: 2
agent:
  desc: null
  value: hyper_ddpg_rnd
agent.details:
  desc: null
  value:
    _target_: agent.hyper_ddpg_rnd.HyperDDPGRNDAgent
    action_shape: ???
    batch_size: 1024
    critic_target_tau: 0.01
    device: cuda
    feature_dim: 50
    hidden_dim: 1024
    init_critic: true
    lr: 0.0001
    name: hyper_ddpg_rnd
    nstep: 3
    num_expl_steps: ???
    obs_shape: ???
    obs_type: ???
    reward_free: false
    rnd_rep_dim: 512
    rnd_scale: 1.0
    stddev_clip: 0.3
    stddev_schedule: 0.2
    update_encoder: false
    update_every_steps: 2
    use_tb: true
    use_wandb: true
batch_size:
  desc: null
  value: 256
device:
  desc: null
  value: cuda
discount:
  desc: null
  value: 0.99
eval_every_frames:
  desc: null
  value: 10000
experiment:
  desc: null
  value: exp
frame_stack:
  desc: null
  value: 3
nstep:
  desc: null
  value: 3
num_eval_episodes:
  desc: null
  value: 10
num_seed_frames:
  desc: null
  value: 4000
num_train_frames:
  desc: null
  value: 200010
obs_type:
  desc: null
  value: pixels
pt_seed:
  desc: null
  value: 1
replay_buffer_num_workers:
  desc: null
  value: 4
replay_buffer_size:
  desc: null
  value: 1000000
reward_free:
  desc: null
  value: false
save_train_video:
  desc: null
  value: false
save_video:
  desc: null
  value: true
seed:
  desc: null
  value: 1
snapshot_base_dir:
  desc: null
  value: ../../../models
snapshot_ts:
  desc: null
  value: 100000
task:
  desc: null
  value: walker_stand
update_encoder:
  desc: null
  value: false
use_tb:
  desc: null
  value: true
use_wandb:
  desc: null
  value: true
